version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.7.3
              environment:
                AUTH_ISSUER: http://localhost:12345
                AUTH_SECRET: lkjlksdldkfjlsdjflsdnfkl
                PYTEST_ADDOPTS: --log-level=debug tests/
            - image: circleci/mongo:3.7.9-ram
            - image: wipac/token-service:latest
              environment:
                port: 12345
                auth_secret: lkjlksdldkfjlsdjflsdnfkl
              command: [python, test_server.py]
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                python -m pytest --tb=short
    deploy:
        docker:
            - image: circleci/buildpack-deps:buster
              environment:
                IMAGE_NAME: wipac/s3-url
        steps:
            - checkout
            - setup_remote_docker
            - run: |
                echo 'export TAG="${CIRCLE_TAG:=latest}"' >> $BASH_ENV
            - run: |
                docker build --target runtime -t $IMAGE_NAME:$TAG .
            - run: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                docker push $IMAGE_NAME:$TAG
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - deploy:
                context: docker
                requires:
                    - test
                filters:
                    branches:
                        only: master
    release:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v?\d+\.\d+\.\d+$/
